logwrapper:
  enabled: true # Highly recommended to enable this module
  path: modules.logwrapper.LogWrapper
  config:
    filename: app.log
    log_level: 'debug' # debug, info, warning, error, critical
    cli_level: 'info' # debug, info, warning, error, critical
  dependencies:
    python:
      - pypubsub
