neopixel:
  enabled: true
  path: 'modules.neopixel.neopx.NeoPx'
  config:
    pin: 12 # Only used for GPIO. GPIO2 and 3 are use for i2c, GPIO10 is used for SPI, GPIO12 is used for GPIO
    protocol: 'SPI' # choose between GPIO, I2C and SPI
    count: 12
    positions: {
      'status1': 0,
      'status2': 1,
      'status3': 2,
      'status4': 3,
      'status5': 4,
      'right' : 5,
      'top_right': 6,
      'top_left' : 7,
      'left' : 8,
      'bottom_left' : 9,
      'bottom_right' : 10,
      'middle': 11,
    }
    brightness: [
        0.2,
        0.2,
        0.2,
        0.2,
        0.2,
        1,
        1,
        1,
        1,
        1,
        1,
        1
    ]
  dependencies:
    python:
      - colour
      - adafruit-circuitpython-seesaw # i2c SUPPORT
      - adafruit-blinka # SPI SUPPORT
      - adafruit-circuitpython-neopixel-spi # SPI SUPPORT
  emotion_analysis:
    enable: false
