ttsmodule:
  enabled: true
  path: "modules.audio.ttsmodule.TTSModule"
  config:
    service: "elevenlabs" # or pyttsx3
    voice_id: "pMsXgVXv3BLzUgSXRplE"
  dependencies:
    python:
      - pyttsx3
      - elevenlabs
    unix:
      - espeak
      - ffmpeg
      - libespeak1
    additional:
      - installers/install-amp.sh