tts:
  enabled: false
  path: "modules.audio.tts.TTS"
  config:
    service: "elevenlabs" # or pyttsx3
    voice_id: "pMsXgVXv3BLzUgSXRplE"
  dependencies:
    python:
      - pyttsx3
      - elevenlabs
